export { default as SCanvas } from "./sCanvas"
export * from "./noise"
export * from "./paths"
export { default as v } from "./vectors"
export * from "./gradient"
export { default as c } from "./collectionOps"
export * from "./types/sol"
export * from "./util"

export * from "./paths/SimplePath"
export * from "./paths/Path"
export * from "./paths/CompoundPath"
export * from "./paths/Arc"
export * from "./paths/Ellipse"
export * from "./paths/Circle"
export * from "./paths/Hatching"
export * from "./paths/HollowArc"
export * from "./paths/Rect"
export * from "./paths/Square"
export * from "./paths/RoundedRect"
export * from "./paths/Star"
export * from "./paths/RegularPolygon"
export * from "./paths/Spiral"
export * from "./paths/Line"
export * from "./paths/Text"
export * from "./palette"
export * from "./shade"
export * from "./render"
