/**
 * Pin the fonts used when rendering sample images.
 *
 * node-canvas draws text through fontconfig, so `sans-serif` means DejaVu
 * Sans on a Linux CI box, Helvetica on a Mac and something else again in a
 * container. That makes the text samples look different on every machine,
 * which no amount of tolerance in the image comparison can paper over.
 *
 * So we ignore the system's fonts entirely: `assets/fonts` holds the three
 * DejaVu faces, and this module points fontconfig at a generated config that
 * exposes only those, with everything else aliased onto them. Same fonts, same
 * metrics, same pixels, everywhere.
 *
 * MUST be called before `canvas` is loaded (fontconfig reads the environment
 * when it initialises), so the scripts that use it import the renderer
 * dynamically afterwards.
 */
import fs from "node:fs"
import os from "node:os"
import path from "node:path"
import { fileURLToPath } from "node:url"

const here = path.dirname(fileURLToPath(import.meta.url))

export const fontDirectory = path.resolve(here, "../assets/fonts")

/** Families the samples ask for, and what each should resolve to. */
const aliases: [family: string, generic: string][] = [
  ["sans", "sans-serif"],
  ["Helvetica", "sans-serif"],
  ["Arial", "sans-serif"],
  ["-apple-system", "sans-serif"],
  ["BlinkMacSystemFont", "sans-serif"],
  ["Segoe UI", "sans-serif"],
  ["Roboto", "sans-serif"],
  ["times", "serif"],
  ["Times", "serif"],
  ["Times New Roman", "serif"],
]

const escapeXml = (value: string) =>
  value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;")

function fontsConf(cacheDirectory: string): string {
  const alias = (family: string, prefer: string, element: string) =>
    `  <alias>
    <family>${escapeXml(family)}</family>
    <${element}><family>${escapeXml(prefer)}</family></${element}>
  </alias>`

  return `<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<!-- Generated by scripts/fonts.ts; edit that instead. -->
<fontconfig>
  <dir>${escapeXml(fontDirectory)}</dir>
  <cachedir>${escapeXml(cacheDirectory)}</cachedir>

  <!-- Order matters: fontconfig applies these in turn to a request's list of
       families, so the named faces have to be turned into generic ones before
       the generic ones are turned into the fonts we actually ship. -->

${aliases.map(([family, generic]) => alias(family, generic, "default")).join("\n")}

  <!-- Anything else (a web font, say) falls back to the sans face rather
       than to whatever fontconfig happens to sort first. -->
  <match target="pattern">
    <edit name="family" mode="append_last"><string>sans-serif</string></edit>
  </match>

${alias("sans-serif", "DejaVu Sans", "prefer")}
${alias("serif", "DejaVu Serif", "prefer")}
${alias("monospace", "DejaVu Sans Mono", "prefer")}
</fontconfig>
`
}

/**
 * Point fontconfig at the bundled fonts. Returns the config path used.
 * Safe to call more than once.
 */
export function useBundledFonts(): string {
  const missing = ["DejaVuSans.ttf", "DejaVuSerif.ttf", "DejaVuSansMono.ttf"]
    .map((file) => path.join(fontDirectory, file))
    .filter((file) => !fs.existsSync(file))

  if (missing.length > 0) {
    throw new Error(
      `Bundled fonts are missing: ${missing.join(", ")}. Sample images cannot be rendered reproducibly without them.`
    )
  }

  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "solandra-fonts-"))
  const cacheDirectory = path.join(directory, "cache")
  fs.mkdirSync(cacheDirectory, { recursive: true })

  const configPath = path.join(directory, "fonts.conf")
  fs.writeFileSync(configPath, fontsConf(cacheDirectory))

  process.env.FONTCONFIG_FILE = configPath
  process.env.FONTCONFIG_PATH = directory

  return configPath
}
